// <auto-generated />
using System;
using LibreriaWebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaWebAPI.Migrations
{
    [DbContext(typeof(LibroDbContext))]
    partial class LibroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("DescripcionAutor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            IdAutor = 1,
                            DescripcionAutor = "Garcia Marquez"
                        },
                        new
                        {
                            IdAutor = 2,
                            DescripcionAutor = "JK Rowling"
                        },
                        new
                        {
                            IdAutor = 3,
                            DescripcionAutor = "Stephen King"
                        },
                        new
                        {
                            IdAutor = 4,
                            DescripcionAutor = "William Shakespeare"
                        },
                        new
                        {
                            IdAutor = 5,
                            DescripcionAutor = "Cervantes"
                        });
                });

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("DescripcionGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            IdGenero = 1,
                            DescripcionGenero = "terror"
                        },
                        new
                        {
                            IdGenero = 2,
                            DescripcionGenero = "policia"
                        },
                        new
                        {
                            IdGenero = 3,
                            DescripcionGenero = "historia"
                        },
                        new
                        {
                            IdGenero = 4,
                            DescripcionGenero = "romantico"
                        },
                        new
                        {
                            IdGenero = 5,
                            DescripcionGenero = "ficcion"
                        });
                });

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_publicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ISBN");

                    b.HasIndex("AutorId");

                    b.HasIndex("GeneroId");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Libro", b =>
                {
                    b.HasOne("Gestion_de_Biblioteca.Model.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_de_Biblioteca.Model.Genero", "Genero")
                        .WithMany("Libros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Gestion_de_Biblioteca.Model.Genero", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
